# Generated by Django 5.2.5 on 2025-09-05 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('teams_enabled', models.BooleanField(default=False)),
                ('slack_enabled', models.BooleanField(default=False)),
                ('teams_webhook_url', models.URLField(blank=True, default='')),
                ('slack_webhook_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notify_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
