# Generated by Django 5.2.7 on 2025-11-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizacaoFV',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(db_column='CODCOLIGADA', null=True)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('idcategoria', models.IntegerField(db_column='IDCATEGORIA', null=True)),
                ('ativo', models.BooleanField(db_column='ATIVO', default=True)),
                ('reccreatedby', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=100, null=True)),
                ('reccreatedon', models.DateTimeField(db_column='RECCREATEDON', null=True)),
                ('recmodifiedby', models.CharField(blank=True, db_column='RECMODIFIEDBY', max_length=100, null=True)),
                ('recmodifiedon', models.DateTimeField(db_column='RECMODIFIEDON', null=True)),
            ],
            options={
                'db_table': 'AUD_FV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoReport',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(db_column='CODCOLIGADA', null=True)),
                ('codaplicacao', models.IntegerField(db_column='CODAPLICACAO', null=True)),
                ('codigo', models.CharField(blank=True, db_column='CODIGO', max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('reccreatedby', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=100, null=True)),
                ('reccreatedon', models.DateTimeField(db_column='RECCREATEDON', null=True)),
                ('recmodifiedby', models.CharField(blank=True, db_column='RECMODIFIEDBY', max_length=100, null=True)),
                ('recmodifiedon', models.DateTimeField(db_column='RECMODIFIEDON', null=True)),
            ],
            options={
                'db_table': 'AUD_REPORT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoSQL',
            fields=[
                ('id', models.CharField(db_column='CODSENTENCA', max_length=100, primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(db_column='CODCOLIGADA', null=True)),
                ('aplicacao', models.CharField(blank=True, db_column='APLICACAO', max_length=100, null=True)),
                ('titulo', models.CharField(blank=True, db_column='TITULO', max_length=255, null=True)),
                ('sentenca', models.TextField(blank=True, db_column='SENTENCA', null=True)),
                ('tamanho', models.IntegerField(db_column='TAMANHO', null=True)),
                ('reccreatedby', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=100, null=True)),
                ('reccreatedon', models.DateTimeField(db_column='RECCREATEDON', null=True)),
                ('recmodifiedby', models.CharField(blank=True, db_column='RECMODIFIEDBY', max_length=100, null=True)),
                ('recmodifiedon', models.DateTimeField(db_column='RECMODIFIEDON', null=True)),
            ],
            options={
                'db_table': 'AUD_SQL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('id_usuario', models.IntegerField(db_column='id_usuario')),
            ],
            options={
                'db_table': 'NOTIFICACAO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(db_column='texto')),
                ('data', models.DateTimeField(auto_now_add=True, db_column='data')),
                ('criado_por', models.IntegerField(blank=True, db_column='criado_por', null=True)),
            ],
            options={
                'db_table': 'Observacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(db_column='nivel', max_length=50)),
            ],
            options={
                'db_table': 'Prioridade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CadastroDependencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aud_sql', models.CharField(blank=True, db_column='id_aud_sql', max_length=100, null=True)),
                ('id_aud_report', models.IntegerField(blank=True, db_column='id_aud_report', null=True)),
                ('id_aud_fv', models.IntegerField(blank=True, db_column='id_aud_fv', null=True)),
                ('id_observacao', models.IntegerField(blank=True, db_column='id_observacao', null=True)),
                ('id_prioridade', models.IntegerField(blank=True, db_column='id_prioridade', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
                ('criado_por', models.IntegerField(blank=True, db_column='criado_por', null=True)),
            ],
            options={
                'db_table': 'Cadastro_Dependencias',
                'managed': True,
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('id_aud_sql__isnull', False), ('id_aud_report__isnull', False), ('id_aud_fv__isnull', False), _connector='OR')), fields=('id_aud_sql', 'id_aud_report', 'id_aud_fv'), name='unique_dependencia_par')],
            },
        ),
    ]
