# Generated by Django 5.2.7 on 2025-10-30 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizacaoFV',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(db_column='CODCOLIGADA', null=True)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('idcategoria', models.IntegerField(db_column='IDCATEGORIA', null=True)),
                ('ativo', models.BooleanField(db_column='ATIVO', default=True)),
            ],
            options={
                'db_table': 'AUD_FV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoReport',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(db_column='CODCOLIGADA', null=True)),
                ('codaplicacao', models.IntegerField(db_column='CODAPLICACAO', null=True)),
                ('codigo', models.CharField(blank=True, db_column='CODIGO', max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
            ],
            options={
                'db_table': 'AUD_REPORT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoSQL',
            fields=[
                ('id', models.IntegerField(db_column='CODSENTENCA', primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(db_column='CODCOLIGADA', null=True)),
                ('aplicacao', models.CharField(blank=True, db_column='APLICACAO', max_length=100, null=True)),
                ('titulo', models.CharField(blank=True, db_column='TITULO', max_length=255, null=True)),
                ('sentenca', models.TextField(blank=True, db_column='SENTENCA', null=True)),
            ],
            options={
                'db_table': 'AUD_SQL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(db_column='nivel', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Prioridade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
                ('texto', models.TextField(db_column='texto')),
                ('data', models.DateTimeField(auto_now_add=True, db_column='data')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Observacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CadastroDependencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
                ('id_aud_sql', models.IntegerField(blank=True, db_column='id_aud_sql', null=True)),
                ('id_aud_report', models.IntegerField(blank=True, db_column='id_aud_report', null=True)),
                ('id_aud_fv', models.IntegerField(blank=True, db_column='id_aud_fv', null=True)),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('id_observacao', models.ForeignKey(blank=True, db_column='id_observacao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizacoes.observacao')),
                ('id_prioridade', models.ForeignKey(blank=True, db_column='id_prioridade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizacoes.prioridade')),
            ],
            options={
                'db_table': 'Cadastro_Dependencias',
                'managed': True,
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('id_aud_sql__isnull', False), ('id_aud_report__isnull', False), ('id_aud_fv__isnull', False), _connector='OR')), fields=('id_aud_sql', 'id_aud_report', 'id_aud_fv'), name='unique_dependencia_par')],
            },
        ),
    ]
