# Generated by Django 5.2.7 on 2025-11-07 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizacaoFV',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(db_column='CODCOLIGADA', null=True)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('idcategoria', models.IntegerField(db_column='IDCATEGORIA', null=True)),
                ('ativo', models.BooleanField(db_column='ATIVO', default=True)),
                ('reccreatedby', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=100, null=True)),
                ('reccreatedon', models.DateTimeField(db_column='RECCREATEDON', null=True)),
            ],
            options={
                'db_table': 'AUD_FV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoReport',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(db_column='CODCOLIGADA', null=True)),
                ('codaplicacao', models.IntegerField(db_column='CODAPLICACAO', null=True)),
                ('codigo', models.CharField(blank=True, db_column='CODIGO', max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('reccreatedby', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=100, null=True)),
                ('reccreatedon', models.DateTimeField(db_column='RECCREATEDON', null=True)),
            ],
            options={
                'db_table': 'AUD_REPORT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoSQL',
            fields=[
                ('codsentenca', models.CharField(db_column='CODSENTENCA', max_length=100, primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(db_column='CODCOLIGADA', null=True)),
                ('aplicacao', models.CharField(blank=True, db_column='APLICACAO', max_length=100, null=True)),
                ('titulo', models.CharField(blank=True, db_column='TITULO', max_length=255, null=True)),
                ('sentenca', models.TextField(blank=True, db_column='SENTENCA', null=True)),
                ('tamanho', models.IntegerField(db_column='TAMANHO', null=True)),
                ('reccreatedby', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=100, null=True)),
                ('reccreatedon', models.DateTimeField(db_column='RECCREATEDON', null=True)),
            ],
            options={
                'db_table': 'AUD_SQL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(db_column='nivel', max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
            ],
            options={
                'db_table': 'Prioridade',
                'ordering': ['nivel'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='titulo', max_length=200)),
                ('descricao', models.TextField(db_column='descricao')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_column='data_hora')),
                ('lida', models.BooleanField(db_column='lida', default=False)),
                ('id_usuario', models.CharField(db_column='id_usuario', max_length=150)),
                ('prioridade', models.ForeignKey(blank=True, db_column='prioridade_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='customizacoes.prioridade')),
            ],
            options={
                'db_table': 'NOTIFICACAO',
                'ordering': ['-data_hora'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CadastroDependencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aud_sql', models.CharField(blank=True, db_column='id_aud_sql', max_length=100, null=True)),
                ('id_aud_report', models.IntegerField(blank=True, db_column='id_aud_report', null=True)),
                ('id_aud_fv', models.IntegerField(blank=True, db_column='id_aud_fv', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
                ('criado_por', models.CharField(db_column='criado_por', max_length=100)),
                ('id_prioridade', models.ForeignKey(blank=True, db_column='id_prioridade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias', to='customizacoes.prioridade')),
            ],
            options={
                'db_table': 'Cadastro_Dependencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DependenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sql', 'SQL'), ('report', 'Report'), ('fv', 'Fórmula')], db_column='tipo', max_length=20)),
                ('id_dependente', models.CharField(db_column='id_dependente', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
                ('cadastro', models.ForeignKey(db_column='cadastro_id', on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='customizacoes.cadastrodependencias')),
            ],
            options={
                'db_table': 'Dependencia_Item',
                'managed': True,
                'unique_together': {('cadastro', 'tipo', 'id_dependente')},
            },
        ),
    ]
