# Generated by Django 5.2.7 on 2025-11-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'managed': True},
        ),
    ]
