# Generated by Django 5.2.7 on 2025-11-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_entry_id', models.IntegerField(db_column='log_entry_id', unique=True)),
                ('objeto_tipo', models.CharField(db_column='objeto_tipo', max_length=50)),
                ('objeto_id', models.CharField(db_column='objeto_id', max_length=100)),
                ('titulo', models.CharField(blank=True, db_column='titulo', max_length=255)),
                ('valor_atual', models.TextField(blank=True, db_column='valor_atual', null=True)),
                ('valor_anterior', models.TextField(blank=True, db_column='valor_anterior', null=True)),
                ('acao', models.CharField(db_column='acao', max_length=50)),
                ('usuario', models.CharField(db_column='usuario', max_length=150)),
                ('data_alteracao', models.DateTimeField(db_column='data_alteracao')),
                ('prioridade_maxima', models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], db_column='prioridade_maxima', default='Baixa', max_length=20)),
                ('status', models.CharField(choices=[('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], db_column='status', default='em_analise', max_length=20)),
                ('observacao', models.TextField(blank=True, db_column='observacao', null=True)),
                ('dependencias_afetadas', models.IntegerField(db_column='dependencias_afetadas', default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
            ],
            options={
                'db_table': 'Historico_Alteracao',
                'ordering': ['-data_alteracao'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='cadastrodependencias',
            name='criado_por',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastrodependencias',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cadastrodependencias',
            name='id_aud_fv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrodependencias',
            name='id_aud_report',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrodependencias',
            name='id_aud_sql',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrodependencias',
            name='id_prioridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias', to='customizacoes.prioridade'),
        ),
        migrations.AlterField(
            model_name='dependenciaitem',
            name='cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='customizacoes.cadastrodependencias'),
        ),
        migrations.AlterField(
            model_name='dependenciaitem',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dependenciaitem',
            name='id_dependente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dependenciaitem',
            name='tipo',
            field=models.CharField(choices=[('sql', 'SQL'), ('report', 'Report'), ('fv', 'Fórmula')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='id_usuario',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='prioridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='customizacoes.prioridade'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
