# Generated by Django 5.2.7 on 2025-10-30 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrodependencias',
            name='id_aud_sql',
            field=models.CharField(blank=True, db_column='id_aud_sql', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizacoes_notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'NOTIFICACAO',
                'managed': True,
            },
        ),
    ]
