# Generated by Django 5.2.5 on 2025-09-05 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('TODOS', 'Todos'), ('MODULO', 'Por Módulo'), ('ITEM', 'Item Específico')], max_length=10)),
                ('modulo', models.CharField(blank=True, default='', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='notificacao',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_originadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alteracao',
            name='customizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes', to='customizacoes.customizacao'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', 'lida', '-criada_em'], name='customizaco_destina_253bcc_idx'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='customizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customizacoes.customizacao'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assinatura',
            unique_together={('usuario', 'escopo', 'modulo', 'customizacao')},
        ),
    ]
