# Generated by Django 5.2.7 on 2025-10-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0002_alter_cadastrodependencias_id_aud_sql_notificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'managed': False},
        ),
    ]
