# Generated by Django 5.2.7 on 2025-10-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0002_assinatura_notificacao_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizacao',
            options={'managed': False, 'ordering': ['nome']},
        ),
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='DBO_NOTIFIC_destina_0ce5a1_idx',
            old_name='customizaco_destina_253bcc_idx',
        ),
        migrations.AlterModelTable(
            name='notificacao',
            table='DBO_NOTIFICACAO',
        ),
    ]
