# Generated by Django 5.2.7 on 2025-11-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0002_alter_notificacao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(db_column='texto')),
                ('data', models.DateTimeField(db_column='data')),
                ('criado_por', models.IntegerField(blank=True, db_column='criado_por', null=True)),
                ('id_dependencia', models.IntegerField(blank=True, db_column='id_dependencia', null=True)),
            ],
            options={
                'db_table': 'HistoricoDependencia',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Observacao',
        ),
        migrations.RemoveConstraint(
            model_name='cadastrodependencias',
            name='unique_dependencia_par',
        ),
        migrations.RemoveField(
            model_name='cadastrodependencias',
            name='id_observacao',
        ),
    ]
