# Generated by Django 5.2.7 on 2025-10-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0003_alter_notificacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='cadastrodependencias',
            name='id_aud_sql',
            field=models.IntegerField(blank=True, db_column='id_aud_sql', null=True),
        ),
        migrations.AlterField(
            model_name='prioridade',
            name='nivel',
            field=models.CharField(db_column='nivel', max_length=50),
        ),
    ]
