# Generated by Django 5.2.7 on 2025-10-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0003_alter_customizacao_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='dbo_NOTIFIC_destina_f4f5b2_idx',
            old_name='DBO_NOTIFIC_destina_0ce5a1_idx',
        ),
        migrations.AlterModelTable(
            name='customizacao',
            table='dbo_AUDFV',
        ),
        migrations.AlterModelTable(
            name='notificacao',
            table='dbo_NOTIFICACAO',
        ),
    ]
