# Generated by Django 5.2.7 on 2025-11-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0003_historicodependencia_delete_observacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoDependencia',
        ),
        migrations.AlterField(
            model_name='cadastrodependencias',
            name='criado_por',
            field=models.CharField(db_column='criado_por', default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
