# Generated by Django 5.2.7 on 2025-10-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0004_rename_dbo_notific_destina_0ce5a1_idx_dbo_notific_destina_f4f5b2_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizacao',
            options={'managed': False},
        ),
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='DBO_NOTIFIC_destina_0ce5a1_idx',
            old_name='dbo_NOTIFIC_destina_f4f5b2_idx',
        ),
        migrations.AlterModelTable(
            name='customizacao',
            table='AUD_FV',
        ),
        migrations.AlterModelTable(
            name='notificacao',
            table='DBO_NOTIFICACAO',
        ),
    ]
