# Generated by Django 5.2.7 on 2025-10-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0005_alter_customizacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizacaoFV',
            fields=[
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=255, null=True)),
                ('descricao_tecnica', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('criado_no_erp_em', models.DateTimeField(blank=True, db_column='RECCREATEDON', null=True)),
                ('alterado_no_erp_em', models.DateTimeField(blank=True, db_column='RECMODIFIEDON', null=True)),
                ('responsavel', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=120, null=True)),
                ('codcoligada', models.IntegerField(blank=True, db_column='CODCOLIGADA', null=True)),
                ('tipo', models.CharField(blank=True, choices=[('FORMULA', 'Fórmula Visual'), ('SQL', 'Consulta SQL'), ('RELATORIO', 'Relatório'), ('OUTRO', 'Outro')], db_column='tipo', max_length=16, null=True)),
                ('status', models.CharField(blank=True, choices=[('ATIVA', 'Ativa'), ('OBSOLETA', 'Obsoleta'), ('EM_REVISAO', 'Em revisão')], db_column='status', max_length=16, null=True)),
                ('versao', models.CharField(blank=True, db_column='versao', max_length=64, null=True)),
                ('responsavel_email', models.EmailField(blank=True, db_column='responsavel_email', max_length=254, null=True)),
                ('modulo', models.CharField(blank=True, db_column='modulo', max_length=120, null=True)),
                ('identificador_erp', models.CharField(blank=True, db_column='identificador_erp_col', max_length=255, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(db_column='ID', primary_key=True, serialize=False)),
                ('categoria', models.IntegerField(blank=True, db_column='IDCATEGORIA', null=True)),
                ('ativo', models.BooleanField(db_column='ATIVO', default=True)),
            ],
            options={
                'db_table': 'AUD_FV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoReport',
            fields=[
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=255, null=True)),
                ('descricao_tecnica', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('criado_no_erp_em', models.DateTimeField(blank=True, db_column='RECCREATEDON', null=True)),
                ('responsavel', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=120, null=True)),
                ('codcoligada', models.IntegerField(blank=True, db_column='CODCOLIGADA', null=True)),
                ('tipo', models.CharField(blank=True, choices=[('FORMULA', 'Fórmula Visual'), ('SQL', 'Consulta SQL'), ('RELATORIO', 'Relatório'), ('OUTRO', 'Outro')], db_column='tipo', max_length=16, null=True)),
                ('status', models.CharField(blank=True, choices=[('ATIVA', 'Ativa'), ('OBSOLETA', 'Obsoleta'), ('EM_REVISAO', 'Em revisão')], db_column='status', max_length=16, null=True)),
                ('versao', models.CharField(blank=True, db_column='versao', max_length=64, null=True)),
                ('responsavel_email', models.EmailField(blank=True, db_column='responsavel_email', max_length=254, null=True)),
                ('modulo', models.CharField(blank=True, db_column='modulo', max_length=120, null=True)),
                ('identificador_erp', models.CharField(blank=True, db_column='identificador_erp_col', max_length=255, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='CODIGO', max_length=100, null=True)),
                ('aplicacao', models.CharField(blank=True, db_column='CODAPLICACAO', max_length=100, null=True)),
                ('alterado_por', models.CharField(blank=True, db_column='USRULTALTERACAO', max_length=120, null=True)),
                ('alterado_no_erp_em', models.DateTimeField(blank=True, db_column='DATAULTALTERACAO', null=True)),
            ],
            options={
                'db_table': 'AUD_REPORT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoSQL',
            fields=[
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=255, null=True)),
                ('descricao_tecnica', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('criado_no_erp_em', models.DateTimeField(blank=True, db_column='RECCREATEDON', null=True)),
                ('alterado_no_erp_em', models.DateTimeField(blank=True, db_column='RECMODIFIEDON', null=True)),
                ('responsavel', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=120, null=True)),
                ('codcoligada', models.IntegerField(blank=True, db_column='CODCOLIGADA', null=True)),
                ('tipo', models.CharField(blank=True, choices=[('FORMULA', 'Fórmula Visual'), ('SQL', 'Consulta SQL'), ('RELATORIO', 'Relatório'), ('OUTRO', 'Outro')], db_column='tipo', max_length=16, null=True)),
                ('status', models.CharField(blank=True, choices=[('ATIVA', 'Ativa'), ('OBSOLETA', 'Obsoleta'), ('EM_REVISAO', 'Em revisão')], db_column='status', max_length=16, null=True)),
                ('versao', models.CharField(blank=True, db_column='versao', max_length=64, null=True)),
                ('responsavel_email', models.EmailField(blank=True, db_column='responsavel_email', max_length=254, null=True)),
                ('modulo', models.CharField(blank=True, db_column='modulo', max_length=120, null=True)),
                ('identificador_erp', models.CharField(blank=True, db_column='identificador_erp_col', max_length=255, null=True)),
                ('id', models.CharField(db_column='CODSENTENCA', max_length=255, primary_key=True, serialize=False)),
                ('tamanho', models.IntegerField(blank=True, db_column='TAMANHO', null=True)),
                ('aplicacao', models.CharField(blank=True, db_column='APLICACAO', max_length=100, null=True)),
                ('conteudo', models.TextField(blank=True, db_column='SENTENCA', null=True)),
            ],
            options={
                'db_table': 'AUD_SQL',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='alteracao',
            options={'managed': False, 'ordering': ['-ocorreu_em']},
        ),
        migrations.AlterModelOptions(
            name='assinatura',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dependencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'managed': False},
        ),
    ]
