# Generated by Django 5.2.5 on 2025-09-05 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customizacoes', '0002_assinatura_notificacao_destinatario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizacaoEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vec', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customizacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='customizacoes.customizacao')),
            ],
        ),
    ]
