# Generated by Django 5.2.7 on 2025-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizacaoEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FV', 'Fórmula Visual'), ('SQL', 'Consulta SQL'), ('REPORT', 'Relatório')], max_length=6)),
                ('customizacao_id', models.IntegerField()),
                ('vec', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tipo', 'customizacao_id'], name='ai_customiz_tipo_7b907d_idx')],
                'unique_together': {('tipo', 'customizacao_id')},
            },
        ),
    ]
